### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alex-lairan** [alex-lairan/azurite#2]
Features : 

- [ ] Multi-db
- [ ] Map finder with Entity
- [ ] AST
- [ ] Send to Mongo.cr
- [ ] Transform BSON to Entity
- Where
  - [ ] Query
  - [ ] Limit
  - [ ] Aggregate
- [ ] Map / Reduce
- [ ] Insert
- [ ] Upsert
- [ ] Update
- [ ] Delete
- [ ] *Bulk Write*
- Types
  - [ ] Int
  - [ ] String
  - [ ] Double
  - [ ] Array
  - [ ] Nested
  - [ ] BinaryData
  - [ ] Bool
  - [ ] Date
  - [ ] Regex
